module.exports = [
    {
      id: "1",
      name: "Women's T-Shirt",
      brand: "Roadstar",
      price: 600,
      size: "M",
      category: "clothing",
    },
    {
      id: "2",
      name: "Women's Shirt",
      brand: "Roadstar",
      price: 800,
      size: "M",
      category: "clothing",
    },
    {
      id: "3",
      name: "Women's T-Shirt",
      brand: "HRX",
      price: 500,
      size: "M",
      category: "clothing",
    },
    {
      id: "4",
      name: "Women's T-Shirt",
      brand: "H&M",
      price: 1000,
      size: "s",
      category: "clothing",
    },
    {
      id: "5",
      name: "Women's Shirt",
      brand: "wrogn",
      price: 700,
      size: "M",
      category: "clothing",
    },
    {
      id: "6",
      name: "Women's Jeans",
      brand: "Roadstar",
      price: 1200,
      size: "32",
      category: "clothing",
    },
    {
      id: "7",
      name: "Women's Kurta",
      brand: "H&M",
      price: 900,
      size: "M",
      category: "clothing",
    },
    {
      id: "8",
      name: "Women's T-Shirt",
      brand: "Mufti",
      price: 800,
      size: "M",
      category: "clothing",
    },
    {
      id: "9",
      name: "Women's Shirt",
      brand: "Pepe jeans",
      price: 600,
      size: "s",
      category: "clothing",
    },
    {
      id: "10",
      name: "Women's T-Shirt",
      brand: "Allen solly",
      price: 1200,
      size: "M",
      category: "clothing",
    },
  ];